Refactor chef 13 style
meringu/code_deploy pull request #6
Opened 2017-07-30 21:43 UTC by meringu

This change refactors the resources to modernize them. Other change is to install the packages directly instead of with the AWS provided installer script. This change should also fix the failing builds in master.

Closes #5

2017-07-30 21:58 UTC, zl4bv commented
Do the CodeDeploy packages come with signatures that can be verified?

2017-07-30 22:08 UTC, meringu commented
> Do the CodeDeploy packages come with signatures that can be verified?

I can't see any info in the docs about the packages being signed http://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install.html. However `remote_file` should check the etag to at least check the file isn't corrupt.

2017-07-30 22:10 UTC, zl4bv requested changes

2017-07-30 22:10 UTC, zl4bv commented on libraries/helper.rb
> +      cmd = shell_out('systemctl | grep "\-\.mount"')
There's a helper in Chef core that may be more reliable at determining if the node uses systemd

```ruby
Chef::Platform::ServiceHelpers.service_resource_providers.include?(:systemd)
```

2017-07-30 22:10 UTC, zl4bv commented on test/integration/default/inspec/code_deploy_spec.rb
> +  describe file('/etc/codedeploy-agent/conf/codedeployagent.yml') do
Consider using the [`yaml`](https://www.inspec.io/docs/reference/resources/yaml/) resource.

2017-07-31 22:09 UTC, zl4bv approved these changes

2017-07-31 22:11 UTC, merged